FROM jetty:9.3-jre8

ADD ./target/scala-2.12/disqus-comment-search-assembly-0.1.0-SNAPSHOT.jar /usr/local/bin/disqus-comment-search-assembly-0.1.0-SNAPSHOT.jar
ADD /scripts/init.sh /usr/local/bin/init.sh
RUN chmod a+x /usr/local/bin/init.sh


RUN mkdir -p /usr/local/share/disqus-comment-search/edu/stanford/nlp/models/pos-tagger/english-left3words/
ADD http://peaceful-lake-98175.herokuapp.com/war_file/english-left3words-distsim.tagger /usr/local/share/disqus-comment-search/edu/stanford/nlp/models/pos-tagger/english-left3words/

RUN mkdir -p /usr/local/share/disqus-comment-search/python
ADD http://peaceful-lake-98175.herokuapp.com/war_file/filter_json_response.py /usr/local/share/disqus-comment-search/python

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/init.sh"]